### ISSUE TITLE
`asyncio` no longer supports generator-based coroutines in 3.12+

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#10116]
What the title says.

On Python 3.11:

```pycon
>python -m asyncio
asyncio REPL 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> def foo():
...     yield from []
...
>>> asyncio.create_task(foo())
<Task pending name='Task-1' coro=<foo() running at <console>:1>>
>>> exit()
```

On Python 3.12:

```pycon
>python -m asyncio
Running PGUpdate|x64 interpreter...
asyncio REPL 3.12.0a7+ (heads/main-dirty:79b9db9295, Apr 28 2023, 22:41:05) [MSC v.1932 64 bit (AMD64)] on win32
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> def foo():
...     yield from []
...
>>> asyncio.create_task(foo())
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\alexw\coding\cpython\Lib\asyncio\__main__.py", line 34, in callback
    coro = func()
           ^^^^^^
  File "<console>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\asyncio\tasks.py", line 377, in create_task
    task = loop.create_task(coro)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\asyncio\base_events.py", line 436, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a coroutine was expected, got <generator object foo at 0x000001E6821AA200>
```

@kumaraditya303 tells me that the same change has been made across `asyncio` on Python 3.12.

We'll need to change annotations like this:

https://github.com/python/typeshed/blob/6f6b1c9135edbe7e6b16b06070f3b12c7bee3a5a/stdlib/asyncio/tasks.pyi#L315-L317

We should branch on `sys.version_info`, like this:

```py
if sys.version_info >= (3, 12):
    def create_task(
        coro: Coroutine[Any, Any, _T], *, name: str | None = None, context: Context | None = None
    ) -> Task[_T]: ...
elif sys.version_info >= (3, 11):
    def create_task(
        coro: Generator[Any, None, _T] | Coroutine[Any, Any, _T], *, name: str | None = None, context: Context | None = None
    ) -> Task[_T]: ...
elif sys.version_info >= (3, 8):
    # etc.
```

We should probably make the change ASAP, so that people testing with the Python 3.12 betas get accurate type hints.

**Comment by srittau** [comment]
Would it make sense to provide a compatibility type alias to avoid the branches?

**Comment by AlexWaygood** [comment]
> Would it make sense to provide a compatibility type alias to avoid the branches?

Yes, good idea!

**Comment by kumaraditya303** [comment]
While I cannot help in any typing stuff, I can help answer any runtime behaviour questions, feel free to ping me for that.

**Comment by max-muoto** [comment]
It seems this was fixed https://github.com/python/typeshed/pull/10177.

Think this can be closed out @AlexWaygood?

**Comment by AlexWaygood** [comment]
> It seems this was fixed in #10177.
> 
> Think this can be closed out @AlexWaygood?

It looks like this has been mostly fixed, but I still see one use of `Generator` in our `asyncio` that looks slightly suspicious: https://github.com/python/typeshed/blob/0c45de1c2667ca52428f2fc0ec9ba07f5d7d4aee/stdlib/asyncio/tasks.pyi#L73

We should verify whether functions annotated with `_FutureLike` actually do still allow generators to be passed in on py312+ before closing this issue.

**Comment by kumaraditya303** [comment]
> We should verify whether functions annotated with _FutureLike actually do still allow generators to be passed in on py312+

They aren't allowed except awaitables.
